AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description:  >- 
  This CloudFormation template creates an AWS IAM policy 
  and role for AppDynamics Cloud Monitoring Integration.
Parameters:
  AppDynamicsExternalId:
    #NoEcho: 'true'
    Type: String
    Description: The role delegation external ID. Generate the external ID in AppDynamics Cloud. 
    MinLength: '2'
    MaxLength: '1224'
    ConstraintDescription: External ID is required 
  AppDynamicsAccountId:
    Type: String
    Description: The AppDynamics Cloud AWS account ID that will assume the IAM role.  
    MinLength: '12'
    MaxLength: '12'
    ConstraintDescription: AppDynamics Cloud Account ID is required. 
  AWSIAMRoleName:
    Type: String
    Description: Update the default AWS IAM role name with AppDynamics Cloud role name 
    Default: AppDynamicsCloudMonitoringRole
    ConstraintDescription: The role name is required. 
  AWSIAMPolicyName:
    Type: String
    Description: Update the default AWS IAM policy name with AppDynamics Cloud policy name
    Default: AppDynamicsCloudMonitoringPolicy
    ConstraintDescription: The policy name is required. 
Resources:
  AppDynamicsCloudMonitoringPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Ref AWSIAMPolicyName
      Path: "/"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - 
          Sid: AllowMonitoring
          Effect: Allow
          Action:
            - elasticloadbalancing:DescribeLoadBalancers
            - ec2:DescribeInstances
            - cloudwatch:GetMetricData
            - ec2:DescribeVpcs
            - ec2:DescribeRegions
            - ec2:DescribeVolumes
            - elasticloadbalancing:DescribeTargetHealth
            - rds:DescribeDBInstances
            - elasticloadbalancing:DescribeTargetGroups
            - ec2:DescribeSubnets
            - cloudwatch:ListMetrics
            - rds:DescribeDBClusters
          Resource: "*"
  AppDynamicsCloudMonitoringRole:
    Type: 'AWS::IAM::Role'
    DependsOn: AppDynamicsCloudMonitoringPolicy
    Properties:
      RoleName: !Ref AWSIAMRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 
                - '${account_id}'
                - { account_id: !Ref AppDynamicsAccountId }
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref AppDynamicsExternalId
      Path: /
      ManagedPolicyArns:
        - !Ref AppDynamicsCloudMonitoringPolicy
Outputs:
  IAMAWSRoleArn:
    Value: !GetAtt AppDynamicsCloudMonitoringRole.Arn   
    Description: Created AWS IAM Role ARN 
