version: '3.9'
services:
  web:
    build: .
    container_name: web-container
    command: node server.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
networks:
  default:
    name: web-network